version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: web-app
    container_name: web-app
    command: /start
    volumes:
      - .:/app
    ports:
      - 8010:8000
    env_file:
      - .env-dev
    depends_on:
      - web-redis
      - web-db

  web-db:
    image: postgres:14-alpine
    container_name: web-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django

  web-redis:
    image: redis:7-alpine
    container_name: web-redis
    volumes:
      - ./redis_data:/data

  web-celery-worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: web-celery-worker
    container_name: web-celery-worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env-dev
    depends_on:
      - web-redis
      - web-db

  web-celery-beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: web-celery-beat
    container_name: web-celery-beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env-dev
    depends_on:
      - web-redis
      - web-db

  web-flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: web-flower
    container_name: web-flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env-dev
    ports:
      - 5557:5555
    depends_on:
      - web-redis
      - web-db

volumes:
  postgres_data:
  redis_data:
